version: "2"
services:
  my-wpdb:
    image: waitheme_my-wpdb
    ports:
      - "8081:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
  my-wp:
    image: waitheme_my-wp
    volumes:
      - ./:/var/www/html/wp-content/themes/
    ports:
      - "8080:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
